version: "2"
plugins:
  fixme:
    enabled: true
  pep8:
    enabled: true
  sonar-python:
    enabled: true
    config:
      tests_patterns:
        - tests/**
  duplication:
    enabled: true
    config:
      languages:
        - python:
            python_version: 3
