version: "2"
plugins:
  fixme:
    enabled: true
  markdownlint:
    enabled: true
  shellcheck:
    enabled: true
  tflint:
    enabled: true
  pep8:
    enabled: true
  pylint:
    enabled: false
  sonar-python:
    enabled: true
    config:
      tests_patterns:
        - tests/**
  duplication:
    enabled: true
    config:
      languages:
        - python:
            python_version: 3
