# You can use this file to define resource usage estimates for Infracost to use when calculating
# the cost of usage-based resource, such as AWS S3 or Lambda.
# `infracost breakdown --usage-file infracost-usage.yml [other flags]`
# See https://infracost.io/usage-file/ for docs
version: 0.1
# resource_type_default_usage:
  ##
  ## The following usage values apply to each resource of the given type, which is useful when you want to define defaults.
  ## All values are commented-out, you can uncomment resource types and customize as needed.
  ##
  # aws_dynamodb_table:
    # monthly_write_request_units: 0 # Monthly write request units in (used for on-demand DynamoDB).
    # monthly_read_request_units: 0 # Monthly read request units in (used for on-demand DynamoDB).
    # storage_gb: 0 # Total storage for tables in GB.
    # pitr_backup_storage_gb: 0 # Total storage for Point-In-Time Recovery (PITR) backups in GB.
    # on_demand_backup_storage_gb: 0 # Total storage for on-demand backups in GB.
    # monthly_data_restored_gb: 0 # Monthly size of restored data in GB.
    # monthly_streams_read_request_units: 0 # Monthly streams read request units.
  # aws_lambda_function:
    # monthly_requests: 0 # Monthly requests to the Lambda function.
    # request_duration_ms: 0 # Average duration of each request in milliseconds.
  # aws_s3_bucket:
    # object_tags: 0 # Total object tags. Only for AWS provider V3.
    # standard:
      # storage_gb: 0.0 # Total storage in GB.
      # monthly_tier_1_requests: 0 # Monthly PUT, COPY, POST, LIST requests (Tier 1).
      # monthly_tier_2_requests: 0 # Monthly GET, SELECT, and all other requests (Tier 2).
      # monthly_select_data_scanned_gb: 0.0 # Monthly data scanned by S3 Select in GB.
      # monthly_select_data_returned_gb: 0.0 # Monthly data returned by S3 Select in GB.
    # intelligent_tiering:
      # frequent_access_storage_gb: 0.0 # Total storage for Frequent Access Tier in GB.
      # infrequent_access_storage_gb: 0.0 # Total storage for Infrequent Access Tier in GB.
      # monitored_objects: 0 # Total objects monitored by the Intelligent Tiering.
      # monthly_tier_1_requests: 0 # Monthly PUT, COPY, POST, LIST requests (Tier 1).
      # monthly_tier_2_requests: 0 # Monthly GET, SELECT, and all other requests (Tier 2).
      # monthly_lifecycle_transition_requests: 0 # Monthly Lifecycle Transition requests.
      # monthly_select_data_scanned_gb: 0.0 # Monthly data scanned by S3 Select in GB.
      # monthly_select_data_returned_gb: 0.0 # Monthly data returned by S3 Select in GB.
      # early_delete_gb: 0.0 # If an archive is deleted within 1 months of being uploaded, you will be charged an early deletion fee per GB.
      # archive_access_storage_gb: 0.0
      # deep_archive_access_storage_gb: 0.0
    # standard_infrequent_access:
      # storage_gb: 0.0 # Total storage in GB.
      # monthly_tier_1_requests: 0 # Monthly PUT, COPY, POST, LIST requests (Tier 1).
      # monthly_tier_2_requests: 0 # Monthly GET, SELECT, and all other requests (Tier 2).
      # monthly_lifecycle_transition_requests: 0 # Monthly Lifecycle Transition requests.
      # monthly_data_retrieval_gb: 0.0 # Monthly data retrievals in GB
      # monthly_select_data_scanned_gb: 0.0 # Monthly data scanned by S3 Select in GB.
      # monthly_select_data_returned_gb: 0.0 # Monthly data returned by S3 Select in GB.
    # one_zone_infrequent_access:
      # storage_gb: 0.0 # Total storage in GB.
      # monthly_tier_1_requests: 0 # Monthly PUT, COPY, POST, LIST requests (Tier 1).
      # monthly_tier_2_requests: 0 # Monthly GET, SELECT, and all other requests (Tier 2).
      # monthly_lifecycle_transition_requests: 0 # Monthly Lifecycle Transition requests.
      # monthly_data_retrieval_gb: 0.0 # Monthly data retrievals in GB
      # monthly_select_data_scanned_gb: 0.0 # Monthly data scanned by S3 Select in GB.
      # monthly_select_data_returned_gb: 0.0 # Monthly data returned by S3 Select in GB.
    # glacier_flexible_retrieval:
      # storage_gb: 0 # Total storage in GB.
      # monthly_tier_1_requests: 0 # Monthly PUT, COPY, POST, LIST requests (Tier 1).
      # monthly_tier_2_requests: 0 # Monthly GET, SELECT, and all other requests (Tier 2).
      # monthly_lifecycle_transition_requests: 0 # Monthly Lifecycle Transition requests.
      # monthly_standard_select_data_scanned_gb: 0.0 # Monthly data scanned by S3 Select in GB (for standard level of S3 Glacier).
      # monthly_standard_select_data_returned_gb: 0.0 # Monthly data returned by S3 Select in GB (for standard level of S3 Glacier).
      # monthly_bulk_select_data_scanned_gb: 0.0 # Monthly data scanned by S3 Select in GB (for bulk level of S3 Glacier)
      # monthly_bulk_select_data_returned_gb: 0.0 # Monthly data returned by S3 Select in GB (for bulk level of S3 Glacier)
      # monthly_expedited_select_data_scanned_gb: 0.0 # Monthly data scanned by S3 Select in GB (for expedited level of S3 Glacier)
      # monthly_expedited_select_data_returned_gb: 0.0 # Monthly data returned by S3 Select in GB (for expedited level of S3 Glacier)
      # monthly_standard_data_retrieval_requests: 0 # Monthly data Retrieval requests (for standard level of S3 Glacier).
      # monthly_expedited_data_retrieval_requests: 0 # Monthly data Retrieval requests (for expedited level of S3 Glacier).
      # monthly_standard_data_retrieval_gb: 0.0 # Monthly data retrievals in GB (for standard level of S3 Glacier).
      # monthly_expedited_data_retrieval_gb: 0.0 # Monthly data retrievals in GB (for expedited level of S3 Glacier).
      # early_delete_gb: 0.0 # If an archive is deleted within 3 months of being uploaded, you will be charged an early deletion fee per GB.
    # glacier_deep_archive:
      # storage_gb: 0.0 # Total storage in GB.
      # monthly_tier_1_requests: 0 # Monthly PUT, COPY, POST, LIST requests (Tier 1).
      # monthly_tier_2_requests: 0 # Monthly GET, SELECT, and all other requests (Tier 2).
      # monthly_lifecycle_transition_requests: 0 # Monthly Lifecycle Transition requests.
      # monthly_standard_data_retrieval_requests: 0 # Monthly data Retrieval requests (for standard level of S3 Glacier).
      # monthly_bulk_data_retrieval_requests: 0 # Monthly data Retrieval requests (for bulk level of S3 Glacier).
      # monthly_standard_data_retrieval_gb: 0.0 # Monthly data retrievals in GB (for standard level of S3 Glacier).
      # monthly_bulk_data_retrieval_gb: 0.0 # Monthly data retrievals in GB (for bulk level of S3 Glacier).
      # early_delete_gb: 0.0 # If an archive is deleted within 6 months of being uploaded, you will be charged an early deletion fee per GB.
  # aws_sns_topic:
    # monthly_requests: 0 # Monthly requests to SNS.
    # request_size_kb: 0.0 # Size of requests to SNS
    # http_subscriptions: 0 # Number of HTTP/HTTPS subscriptions
    # email_subscriptions: 0 # Number of Email/Email-JSON subscriptions
    # kinesis_subscriptions: 0 # Number of Kinesis Firehose subscriptions
    # mobile_push_subscriptions: 0 # Number of Mobile Push subscriptions
    # macos_subscriptions: 0 # Number of MacOS subscriptions
    # sms_subscriptions: 0 # Number of SMS subscriptions
    # sms_notification_price: 0.0075 # Average price for each SMS notification
  # aws_sns_topic_subscription:
    # monthly_requests: 0 # (DEPRECATED use aws_sns_topic.monthly_requests instead) Monthly requests to SNS.
    # request_size_kb: 0 # (DEPRECATED use aws_sns_topic.request_size_kb instead) Size of requests to SNS, billed in 64KB chunks. So 1M requests at 128KB uses 2M requests.
  # aws_sqs_queue:
    # monthly_requests: 0.0 # Monthly requests to SQS.
    # request_size_kb: 0 # Size of requests to SQS, billed in 64KB chunks. So 1M requests at 128KB uses 2M requests.
resource_usage:
  aws_dynamodb_table.table:
    monthly_write_request_units: 0 # Monthly write request units in (used for on-demand DynamoDB).
    monthly_read_request_units: 2 # Monthly read request units in (used for on-demand DynamoDB).
    storage_gb: 0 # Total storage for tables in GB.
    # pitr_backup_storage_gb: 0 # Total storage for Point-In-Time Recovery (PITR) backups in GB.
    # on_demand_backup_storage_gb: 0 # Total storage for on-demand backups in GB.
    # monthly_data_restored_gb: 0 # Monthly size of restored data in GB.
    # monthly_streams_read_request_units: 0 # Monthly streams read request units.
  aws_s3_bucket.storage:
    # object_tags: 0 # Total object tags. Only for AWS provider V3.
    standard:
      storage_gb: 0.0 # Total storage in GB.
      # monthly_tier_1_requests: 0 # Monthly PUT, COPY, POST, LIST requests (Tier 1).
      # monthly_tier_2_requests: 0 # Monthly GET, SELECT, and all other requests (Tier 2).
      # monthly_select_data_scanned_gb: 0.0 # Monthly data scanned by S3 Select in GB.
      # monthly_select_data_returned_gb: 0.0 # Monthly data returned by S3 Select in GB.
    # intelligent_tiering:
      # frequent_access_storage_gb: 0.0 # Total storage for Frequent Access Tier in GB.
      # infrequent_access_storage_gb: 0.0 # Total storage for Infrequent Access Tier in GB.
      # monitored_objects: 0 # Total objects monitored by the Intelligent Tiering.
      # monthly_tier_1_requests: 0 # Monthly PUT, COPY, POST, LIST requests (Tier 1).
      # monthly_tier_2_requests: 0 # Monthly GET, SELECT, and all other requests (Tier 2).
      # monthly_lifecycle_transition_requests: 0 # Monthly Lifecycle Transition requests.
      # monthly_select_data_scanned_gb: 0.0 # Monthly data scanned by S3 Select in GB.
      # monthly_select_data_returned_gb: 0.0 # Monthly data returned by S3 Select in GB.
      # early_delete_gb: 0.0 # If an archive is deleted within 1 months of being uploaded, you will be charged an early deletion fee per GB.
      # archive_access_storage_gb: 0.0
      # deep_archive_access_storage_gb: 0.0
    # standard_infrequent_access:
      # storage_gb: 0.0 # Total storage in GB.
      # monthly_tier_1_requests: 0 # Monthly PUT, COPY, POST, LIST requests (Tier 1).
      # monthly_tier_2_requests: 0 # Monthly GET, SELECT, and all other requests (Tier 2).
      # monthly_lifecycle_transition_requests: 0 # Monthly Lifecycle Transition requests.
      # monthly_data_retrieval_gb: 0.0 # Monthly data retrievals in GB
      # monthly_select_data_scanned_gb: 0.0 # Monthly data scanned by S3 Select in GB.
      # monthly_select_data_returned_gb: 0.0 # Monthly data returned by S3 Select in GB.
    # one_zone_infrequent_access:
      # storage_gb: 0.0 # Total storage in GB.
      # monthly_tier_1_requests: 0 # Monthly PUT, COPY, POST, LIST requests (Tier 1).
      # monthly_tier_2_requests: 0 # Monthly GET, SELECT, and all other requests (Tier 2).
      # monthly_lifecycle_transition_requests: 0 # Monthly Lifecycle Transition requests.
      # monthly_data_retrieval_gb: 0.0 # Monthly data retrievals in GB
      # monthly_select_data_scanned_gb: 0.0 # Monthly data scanned by S3 Select in GB.
      # monthly_select_data_returned_gb: 0.0 # Monthly data returned by S3 Select in GB.
    # glacier_flexible_retrieval:
      # storage_gb: 0 # Total storage in GB.
      # monthly_tier_1_requests: 0 # Monthly PUT, COPY, POST, LIST requests (Tier 1).
      # monthly_tier_2_requests: 0 # Monthly GET, SELECT, and all other requests (Tier 2).
      # monthly_lifecycle_transition_requests: 0 # Monthly Lifecycle Transition requests.
      # monthly_standard_select_data_scanned_gb: 0.0 # Monthly data scanned by S3 Select in GB (for standard level of S3 Glacier).
      # monthly_standard_select_data_returned_gb: 0.0 # Monthly data returned by S3 Select in GB (for standard level of S3 Glacier).
      # monthly_bulk_select_data_scanned_gb: 0.0 # Monthly data scanned by S3 Select in GB (for bulk level of S3 Glacier)
      # monthly_bulk_select_data_returned_gb: 0.0 # Monthly data returned by S3 Select in GB (for bulk level of S3 Glacier)
      # monthly_expedited_select_data_scanned_gb: 0.0 # Monthly data scanned by S3 Select in GB (for expedited level of S3 Glacier)
      # monthly_expedited_select_data_returned_gb: 0.0 # Monthly data returned by S3 Select in GB (for expedited level of S3 Glacier)
      # monthly_standard_data_retrieval_requests: 0 # Monthly data Retrieval requests (for standard level of S3 Glacier).
      # monthly_expedited_data_retrieval_requests: 0 # Monthly data Retrieval requests (for expedited level of S3 Glacier).
      # monthly_standard_data_retrieval_gb: 0.0 # Monthly data retrievals in GB (for standard level of S3 Glacier).
      # monthly_expedited_data_retrieval_gb: 0.0 # Monthly data retrievals in GB (for expedited level of S3 Glacier).
      # early_delete_gb: 0.0 # If an archive is deleted within 3 months of being uploaded, you will be charged an early deletion fee per GB.
    # glacier_deep_archive:
      # storage_gb: 0.0 # Total storage in GB.
      # monthly_tier_1_requests: 0 # Monthly PUT, COPY, POST, LIST requests (Tier 1).
      # monthly_tier_2_requests: 0 # Monthly GET, SELECT, and all other requests (Tier 2).
      # monthly_lifecycle_transition_requests: 0 # Monthly Lifecycle Transition requests.
      # monthly_standard_data_retrieval_requests: 0 # Monthly data Retrieval requests (for standard level of S3 Glacier).
      # monthly_bulk_data_retrieval_requests: 0 # Monthly data Retrieval requests (for bulk level of S3 Glacier).
      # monthly_standard_data_retrieval_gb: 0.0 # Monthly data retrievals in GB (for standard level of S3 Glacier).
      # monthly_bulk_data_retrieval_gb: 0.0 # Monthly data retrievals in GB (for bulk level of S3 Glacier).
      # early_delete_gb: 0.0 # If an archive is deleted within 6 months of being uploaded, you will be charged an early deletion fee per GB.
  module.api.aws_lambda_function.lambda:
    monthly_requests: 0 # Monthly requests to the Lambda function.
    request_duration_ms: 0 # Average duration of each request in milliseconds.
  module.bot.aws_lambda_function.lambda:
    monthly_requests: 0 # Monthly requests to the Lambda function.
    request_duration_ms: 0 # Average duration of each request in milliseconds.
  aws_sns_topic.admin:
    monthly_requests: 43200 # Monthly requests to SNS.
    request_size_kb: 2.0 # Size of requests to SNS
    # http_subscriptions: 0 # Number of HTTP/HTTPS subscriptions
    # email_subscriptions: 0 # Number of Email/Email-JSON subscriptions
    # kinesis_subscriptions: 0 # Number of Kinesis Firehose subscriptions
    # mobile_push_subscriptions: 0 # Number of Mobile Push subscriptions
    # macos_subscriptions: 0 # Number of MacOS subscriptions
    # sms_subscriptions: 0 # Number of SMS subscriptions
    # sms_notification_price: 0.0075 # Average price for each SMS notification
  aws_sqs_queue.admin:
    monthly_requests: 43200.0 # Monthly requests to SQS.
    request_size_kb: 2 # Size of requests to SQS, billed in 64KB chunks. So 1M requests at 128KB uses 2M requests.
  ##
  ## The following usage values apply to individual resources and override any value defined in the resource_type_default_usage section.
  ## All values are commented-out, you can uncomment resources and customize as needed.
  ##
  # aws_sns_topic_subscription.queue:
    # monthly_requests: 0 # (DEPRECATED use aws_sns_topic.monthly_requests instead) Monthly requests to SNS.
    # request_size_kb: 0 # (DEPRECATED use aws_sns_topic.request_size_kb instead) Size of requests to SNS, billed in 64KB chunks. So 1M requests at 128KB uses 2M requests.
